### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by calpa** [calpa/blog#20]
1. Update badges
1.1. Travis CI: [![TravisCI](https://travis-ci.org/calpa/blog.svg?branch=master)](https://travis-ci.org/calpa/blog)
1.2. CodeFactor: [![CodeFactor](https://www.codefactor.io/repository/github/calpa/blog/badge)](https://www.codefactor.io/repository/github/calpa/blog)

2. Fix typos (any)
3. Update Responsive Screenshot

**Comment by MaisaMilena** [comment]
I'll do it

**Comment by calpa** [comment]
@MaisaMilena Thank you

**Comment by mariokcy** [comment]
Update badges?
