### ISSUE TITLE
Fix ''url' is missing in props validation' issue in src\pages\tags\index.js

### ISSUE THREAD

**Issue by calpa** [calpa/blog#33]
[CodeFactor](https://www.codefactor.io/repository/github/calpa/blog) found an issue: 'url' is missing in props validation

It's currently on:
[src\pages\tags\index.js:37
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/pages/tags/index.js#L37)

**Comment by sonumeewa** [comment]
I'll work on this.

**Comment by whathejoe** [comment]
Can I take this?

**Comment by fabricionaweb** [comment]
Is still happing?

**Comment by calpa** [comment]
@fabricionaweb No...
