### ISSUE TITLE
Fix ''location' is missing in props validation' issue in src\pages\tags\index.js

### ISSUE THREAD

**Issue by calpa** [calpa/blog#35]
[CodeFactor](https://www.codefactor.io/repository/github/calpa/blog) found an issue: 'location' is missing in props validation

It's currently on:
[src\pages\tags\index.js:170
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/pages/tags/index.js#L170)

**Comment by MCLofton** [comment]
I'll look into it.
