### ISSUE TITLE
Extract contentful management system

### ISSUE THREAD

**Issue by calpa** [calpa/blog#40]
GatsbyJS has provided the ability to query data from any (remote) source, and contentful is selected in the early stage of this blog system.

For now, API_SPACE_ID and API_TOKEN are used to query the contentful database.

I purposed that query from github gist or other free database with filled data, instead of bundled with contentful.

You may have a look at https://github.com/calpa/blog/blob/master/gatsby/getPosts.js

**Comment by DeViL3998** [comment]
Can you please elaborate what i have to do?

**Comment by calpa** [comment]
@DeViL3998 Thank you for your interest.

For now, the blog system is using GatsbyJS, and querying the data from Contentful Management System.

This is a front end system and should be separated from the backend api.

Here is the code of querying:
https://github.com/calpa/blog/blob/master/gatsby/getPosts.js#L8

You may use [current blog data](https://cdn.contentful.com/spaces/n3ctvxixp1mr/entries?access_token=c69c0fe3b7b6f55e5ab0cedeaab8d187867cf3b1e6995e6253a78ccfb092233b) to have a look at the provided data.

The above one was generated by Contentful, though only some data field written in README.md are required. 

TODO:
1. Change the settings in `.env` from API_SPACE_ID, API_TOKEN to others
1. Change `blog/getPosts.js` settings
1. Provide a mock data that can query the correct types of data

I think that the mock data is stored in a new folder such as `mock` would be a good idea.

For security issue, the API_TOKEN and API_SPACE_ID will be regenerated after this issue is solved.

**Comment by DeViL3998** [comment]
i'm looking into it.
