### ISSUE TITLE
Missing an explicit type attribute for button

### ISSUE THREAD

**Issue by calpa** [calpa/blog#42]
[CodeFactor](https://www.codefactor.io/repository/github/calpa/blog) found multiple issues last seen at dd755fdb74ea5b8aa375a8f4c61cc72acc9c3e4e:

#### Missing an explicit type attribute for button
[src\pages\tags\index.js:141
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/pages/tags/index.js#L141)[src\components\Navbar\index.js:21
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/components/Navbar/index.js#L21)[src\components\Navbar\NavItem\Dropdown\index.js:6
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/components/Navbar/NavItem/Dropdown/index.js#L6)

**Comment by adamk1230** [comment]
I can help with this.

**Comment by DeViL3998** [comment]
I want to do this.

**Comment by calpa** [comment]
@DeViL3998 I am sorry that this issue is assigned to @adamk1230, so you may look at other issue as well.

**Comment by calpa** [comment]
No, solved in #54
