### ISSUE TITLE
Update README.md (data/config.js)

### ISSUE THREAD

**Issue by calpa** [calpa/blog#45]
Like Hexo, this project is using a config file to mutate the important parts of blog system.

However, the documentation of data/config.js is missing in README.md

TODO:

1. Add data/config.js explanation in markdown code block
2. It would be better if you can remove nouse data in data/config.js.

The config file is in:
https://github.com/calpa/blog/blob/master/data/config.js

**Comment by SarahLizDettloff** [comment]
@calpa, starting work on this now. 🎃
