### ISSUE TITLE
Fix 'Unable to resolve path to module '*'.' issue in many files

### ISSUE THREAD

**Issue by calpa** [calpa/blog#55]
After the eslint plugin is updated, the modules seem to be not found.

Though, the packages are installed correctly.

[CodeFactor](https://www.codefactor.io/repository/github/calpa/blog) found an issue: Unable to resolve path to module 'react'.

It's currently on:
[src\templates\blog-post.js:4
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/templates/blog-post.js#L4)Commit dfca9556fb1f9ff02cba85531f35f5e3365ac948

**Comment by pnkapadia6** [comment]
@calpa Can I take this up?

**Comment by calpa** [comment]
Yes.

@fabricionaweb You may have a look at this issue, more information is provided on: [src\templates\blog-post.js:4](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/templates/blog-post.js#L4)
