### ISSUE TITLE
Fix propType is not required, but has no corresponding defaultProp declaration in src\html.js

### ISSUE THREAD

**Issue by calpa** [calpa/blog#58]
[CodeFactor](https://www.codefactor.io/repository/github/calpa/blog) found multiple issues:

#### propType "body" is not required, but has no corresponding defaultProp declaration.
[src\html.js:65
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/html.js#L65)Commit dd755fdb74ea5b8aa375a8f4c61cc72acc9c3e4e

#### propType "htmlAttributes" is not required, but has no corresponding defaultProp declaration.
[src\html.js:55
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/html.js#L55)Commit 106dc22b19372fc565c64cda5a11bbf389e34939

#### propType "headComponents" is not required, but has no corresponding defaultProp declaration.
[src\html.js:56
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/html.js#L56)Commit 106dc22b19372fc565c64cda5a11bbf389e34939

#### propType "bodyAttributes" is not required, but has no corresponding defaultProp declaration.
[src\html.js:60
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/html.js#L60)Commit 106dc22b19372fc565c64cda5a11bbf389e34939

#### propType "preBodyComponents" is not required, but has no corresponding defaultProp declaration.
[src\html.js:61
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/html.js#L61)Commit 106dc22b19372fc565c64cda5a11bbf389e34939

#### propType "postBodyComponents" is not required, but has no corresponding defaultProp declaration.
[src\html.js:66
](https://www.codefactor.io/repository/github/calpa/blog/source/master/src/html.js#L66)Commit 106dc22b19372fc565c64cda5a11bbf389e34939

**Comment by jmartin84** [comment]
I can take this
